version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "database"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "eeba.haxhaja@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "eeeeeeee"
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: