version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "database"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9091:8080"
    depends_on:
      - postgres

  backend:
    image: springboot-backend-app
    container_name: springboot-backend
    depends_on:
      - postgres
    ports:
      - "8081:8081"

volumes:
  postgres_data:
