version: '3.8'

services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "database"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9091:8080"
    depends_on:
      - postgresql

  paperlessrest:
    build:
      context: ./rest_api 
      dockerfile: Dockerfile
    container_name: paperlessrest
    depends_on:
      - postgresql
    ports:
      - "8081:8081"

  web_ui:
    build:
      context: ./web_ui 
      dockerfile: Dockerfile
    container_name: webui
    ports:
      - "80:80"
    depends_on:
      - paperlessrest

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090" # Console
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9090"
    volumes:
      - ./minio/data:/data
    restart: always
  
  paperlessservice:
    build:
      context: ./ocr_worker 
      dockerfile: Dockerfile
    container_name: paperlessservice
    depends_on:
      - rabbitmq
      - minio
    ports:
      - "8082:8082"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"  # Quote the wildcard character
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password
    ports:
      - "3000:3000"  # Grafana UI port
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  postgres_data:
  es-data:
    driver: local
  grafana-data:
    driver: local