version: '3.8'

services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "database"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9091:8080"
    depends_on:
      - postgresql

  paperlessrest:
    build:
      context: ./rest_api 
      dockerfile: Dockerfile
    container_name: paperlessrest
    depends_on:
      - postgresql
    ports:
      - "8081:8081"

  web_ui:
    build:
      context: ./web_ui 
      dockerfile: Dockerfile
    container_name: webui
    ports:
      - "80:80"
    depends_on:
      - paperlessrest

volumes:
  postgres_data: